[package]
version = "0.1.0"
name = "sp1-merkle-proof"
edition = "2021"

[dependencies]
sp1-zkvm = "3.4.0"
crypto-ops = { path = "../../crypto-ops" }
serde_json = "1"
borsh = { version = "1.5.3", features = ["derive"] }
