[package]
version = "0.1.0"
name = "program-tx-recursive"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
merkle-lib = { path = "../lib" }
serde_json = "1"
